# Generated by Django 4.0.2 on 2022-03-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_email', models.EmailField(max_length=254)),
                ('doctor_name', models.CharField(max_length=50)),
                ('app_date', models.DateField()),
                ('app_time', models.TimeField()),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('doctor_first_name', models.CharField(max_length=50)),
                ('doctor_last_name', models.CharField(max_length=50)),
                ('doctor_email_id', models.EmailField(max_length=254)),
                ('patient_email_id', models.EmailField(max_length=254, unique=True)),
                ('doctor_phone_number', models.CharField(max_length=10)),
                ('recommended_tests', models.CharField(max_length=100)),
                ('diagnosis_comments', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('blood_group', models.CharField(max_length=5)),
                ('department', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('blood_group', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('doctor_first_name', models.CharField(max_length=50)),
                ('doctor_last_name', models.CharField(max_length=50)),
                ('doctor_email_id', models.EmailField(max_length=254)),
                ('patient_email_id', models.EmailField(max_length=254, unique=True)),
                ('doctor_phone_number', models.CharField(max_length=15)),
                ('doctor_address', models.CharField(max_length=200)),
                ('medicine', models.CharField(max_length=500)),
                ('dosage', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('test_time', models.TimeField()),
                ('birthdate', models.DateField()),
                ('patient_email_id', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('test_name', models.CharField(max_length=200)),
                ('test_result', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=500)),
                ('reference_doctor', models.CharField(max_length=30)),
                ('reference_doctor_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
