# Generated by Django 4.0.3 on 2022-03-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_welcome', '0002_remove_patient_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_email', models.EmailField(max_length=254, unique=True)),
                ('doctor_name', models.CharField(max_length=50)),
                ('app_date', models.DateField()),
                ('app_time', models.TimeField()),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
