# Generated by Django 4.0.3 on 2022-03-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_welcome', '0002_remove_patient_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('doctor_first_name', models.CharField(max_length=50)),
                ('doctor_last_name', models.CharField(max_length=50)),
                ('doctor_email_id', models.EmailField(max_length=254, unique=True)),
                ('patient_email_id', models.EmailField(max_length=254, unique=True)),
                ('doctor_phone_number', models.CharField(max_length=15)),
                ('doctor_address', models.CharField(max_length=200)),
                ('medicine', models.CharField(max_length=500)),
                ('dosage', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
