# Generated by Django 4.0.3 on 2022-03-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_welcome', '0003_prescription'),
        ('hms_welcome', '0004_alter_appointment_patient_email'),
    ]

    operations = [
    ]
