# Generated by Django 4.0.3 on 2022-03-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_welcome', '0005_merge_20220316_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('doctor_first_name', models.CharField(max_length=50)),
                ('doctor_last_name', models.CharField(max_length=50)),
                ('doctor_email_id', models.EmailField(max_length=254, unique=True)),
                ('patient_email_id', models.EmailField(max_length=254, unique=True)),
                ('doctor_phone_number', models.CharField(max_length=10)),
                ('diagnosis_comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('test_time', models.TimeField()),
                ('birthdate', models.DateField()),
                ('patient_email_id', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('test_name', models.CharField(max_length=200)),
                ('test_result', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=500)),
                ('reference_doctor', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='prescription',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
