# Generated by Django 4.0.3 on 2022-03-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_welcome', '0006_diagnosis_report_alter_prescription_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=500)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
