# Generated by Django 4.0.3 on 2022-03-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_welcome', '0007_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('test_time', models.TimeField()),
                ('birthdate', models.DateField()),
                ('patient_email_id', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('test_name', models.CharField(max_length=200)),
                ('test_status', models.CharField(max_length=1000)),
            ],
        ),
    ]
