# Generated by Django 4.0.3 on 2022-03-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_welcome', '0008_test_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_request',
            name='patient_email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
