# Generated by Django 4.0.3 on 2022-03-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_welcome', '0009_alter_test_request_patient_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance_Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=200)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_visible', models.BooleanField()),
                ('policy_name', models.CharField(max_length=200)),
                ('policy_discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('approved', models.BooleanField(default=False)),
                ('requested', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
