# Generated by Django 4.0.3 on 2022-03-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_welcome', '0010_insurance_policy_insurance_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=254)),
                ('case_numeber', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
