# Generated by Django 4.0.3 on 2022-04-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_welcome', '0013_remove_transaction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malicious_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('failed_login_attempts', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='recommended_tests',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='doctor_email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor_email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
