# Generated by Django 4.0.3 on 2022-04-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_welcome', '0015_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='patient_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='reference_doctor',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
