# Generated by Django 4.0.3 on 2022-04-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_welcome', '0016_employee_completed_report_patient_visible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='completed',
        ),
        migrations.AddField(
            model_name='malicious_login',
            name='email',
            field=models.EmailField(default='riya.2398@gmail.com', max_length=254),
        ),
    ]
