# Generated by Django 4.0.3 on 2022-04-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_welcome', '0017_remove_employee_completed_malicious_login_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
